# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lectures',
        ),
        migrations.AddField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(to='manytomany.Student'),
        ),
    ]
